name: Convert Markdown to PDF

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Pandoc and LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive texlive-latex-extra

    - name: Convert README.md to PDF
      run: |
        mkdir -p output
        pandoc README.md -o output/README.pdf --from markdown --template eisvogel --listings

    - name: Upload PDF
      uses: actions/upload-artifact@v2
      with:
        name: README-pdf
        path: output/README.pdf
